# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DB_HOST: your-rds-endpoint.amazonaws.com
  DB_USER: LW4gImFkbWluIiANCg==
  DB_PASS: LW4gIjEyMzQ1NiIgDQo=
  DB_NAME: auth_demo
